<?php require "../includes/header.php" ?>
<?php require "../config/config.php" ?>

<?php

// After login -- below code will helps use not to redirect user to login page by typing "localhost/forum/auth/login.php".
if (isset($_SESSION['username'])) {
  header("location: " . APPURL . "");
}

// To check weather the user click on the 'Login' button:
if (isset($_POST['login'])) {
  // Validating the control or not empty:
  if (empty($_POST['email']) or empty($_POST['password'])) {
    echo "<script> alert('one or more input or empty'); </script>";
  } else {
    // Read user given data in login.php:
    $email = $_POST['email'];
    $password = $_POST['password'];

    // write the query to valid the user data:
    $login = $conn->query("SELECT * FROM users WHERE email = '$email'");

    // Execute the query:
    $login->execute();

    // Fetch the data generated by query [like array by using -> FETCH_ASSOC] and store in '$fetch' variable:
    // Note:- To validate password $fetch is used.
    $fetch = $login->fetch(PDO::FETCH_ASSOC);

    // below code[condition] will validate the email:
    if ($login->rowCount() > 0) {

      // below code[condition] is to validate the password:
      if (password_verify($password, $fetch['password'])) {
        // If login data is valid then I will store the username in a session and redirect user to index.php:
        // display the session data in index page on top right corner.
        // Note: $_SESSION['session varaible'] = $fetch['column name'];
        // Note: Please refer 'header.php' where I have 'started the session'. "Because session should started in all the page header".
        $_SESSION['username'] = $fetch['username'];

        $_SESSION['user_id'] = $fetch['id'];
        $_SESSION['email'] = $fetch['email'];
        $_SESSION['user_image'] = $fetch['image'];

        // Note: Since we are in inner folder so we can't write 'index.php' directly
        //      So we use APPURL created in 'header.php'
        header("location: " . APPURL . "");
      } else {
        echo "<script> alert('email or password is wrong'); </script>";
      }
    } else {
      echo "<script> alert('email or password is wrong'); </script>";
    }
  }
}

?>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="main-col">
        <div class="block">
          <h1 class="pull-left">Login</h1>
          <h4 class="pull-right">A Simple Forum</h4>
          <div class="clearfix"></div>
          <hr>
          <form role="form" method="post" action="login.php">

            <div class="form-group">
              <label>Email Address*</label> <input type="email" class="form-control" name="email" placeholder="Enter Your Email Address">
            </div>

            <div class="form-group">
              <label>Password*</label> <input type="password" class="form-control" name="password" placeholder="Enter A Password">
            </div>

            <input name="login" type="submit" class="color btn btn-default" value="Login" />
          </form>
        </div>
      </div>
    </div>
    <?php require "../includes/footer.php" ?>